[tool.poetry]
name = "rag-demo"
version = "0.1.0"
description = ""
authors = ["Jason Koo <jalakoo@gmail.com>"]
readme = "README.md"
packages = [{include = "rag_demo"}]

[tool.poetry.dependencies]
python = "^3.11"
boto3 = ">=1.28.57"
awscli = ">=1.29.57"
botocore = ">=1.31.57"
retry = "0.9.2"
langchain = "0.0.314"
streamlit = "1.27.2"
streamlit-chat = "0.1.1"
streamlit-chat-media = "0.0.4"
numpy = "^1.26.2"
pandas = "^2.1.4"
requests = "^2.31.0"
plotly = "5.15.0"
tqdm = "^4.66.1"
altair = "<5"
segment-analytics-python = "^2.2.3"
neo4j = "^5.16.0"
streamlit-feedback = "^0.1.3"
langchain-openai = "^0.0.2.post1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
